### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by Bakuryu** [glat/MultiLinter#1]
The instructions are very general and I am finding it hard to figure out how this plugin actually works. I really would like something that I could lint my scss directly in VS, but I cannot figure out how this works, or why its not working. My project has sass-lint installed locally so I changed the config to local, but nothing happens and I don't see any errors.

**Comment by glat** [comment]
I know it does not works out of the box. I'll try to improve docs.

This extension in based on a json config file you've to place in your profile directory. This config file extends the default one hardcoded in. You can find the base config in this repo.

As you can see in that file all linters are by default disabled. You need to enable your favourite ones and defines on which extensions they've to work. Such as example by config file is:

{
    "eslint": {
        "enabled": true,
        "fileExtensions": "js"
    },
    "stylelint": {
        "enabled": true,
        "fileExtensions": "scss,css"
    }
}

Because I use eslint for javascript files (.js) and stylelint for style files (.css/.scss)

So, first creates this file in your user profile directory, then open any file to lint.
